menu:
  img: /u/base/logo.svg
  items:
  - label: Inicio
    url: /
  - label: Conócenos
    url: /nosotros/
  - label: Servicios
    items:
    - label: Autoconsumo industrial
      url: /autoconsumo-fotovoltaico/
    - label: Instalaciones Flotantes
      url: /instalaciones-solares-flotantes/
    - label: Gestión CAE
      url: /gestion-cae/
    - label: Bombeo solar
      url: /bombeo-solar/
    - label: Ingeniería
      url: /ingenieria/
    - label: Eficiencia energética
      url: /eficiencia-energetica/
    - label: Hydrox
      url: /hydrox/
  - label: Proyectos
    url: /proyectos/
  - label: Precios E.
    url: /precio-electricidad/
  - label: Actualidad
    url: /actualidad/
  - label: Contacto
    url: /contacto/
    btn: cta
callnows:
- type: whatsapp
  label: 621 056 510
- type: phone
  label: 968 27 16 89
footer:
  dots:
  - url: https://www.facebook.com/Solventiee/
  - url: https://www.instagram.com/solventie_/
  - url: https://www.linkedin.com/company/solventie/
  - url: https://g.page/r/CT7T0hQ29sriEB0
  boxes:
  - md: |
      - ::none:: [Autoconsumo Industrial](/autoconsumo-fotovoltaico/)
      - ::none:: [Instalaciones Flotantes](/instalaciones-solares-flotantes/)
      - ::none:: [Gestión CAE](/gestion-cae/)
      - ::none:: [Bombeo Solar](/bombeo-solar/)
      - ::none:: [Ingeniería](/ingenieria/)
      - ::none:: [Eficiencia Energética](/eficiencia-energetica/)
      - ::none:: [Hydrox](/hydrox/)
  - md: |
      - ::none:: [Conócenos](/nosotros/)
      - ::none:: [Proyectos](/proyectos/)
      - ::none:: [Precio de la Electricidad](/precio-electricidad/)
      - ::none:: [Actualidad](/actualidad/)
      - ::none:: [Contacto](/contacto/)
      - ::none:: [© Solvent](/)
  - md: |
      - ::none:: [Apoyos](/apoyos/ "[nofollow]")
      - ::none:: [Avisos Legales](/legal/ "[nofollow]")
      - ::none:: [Política de Privacidad](/privacidad/ "[nofollow]")
      - ::none:: [Política de Cookies](/cookies/ "[nofollow]")
      - ::none:: [Política de Calidad y Medio Ambiente](/politica-calidad-medio-ambiente/ "[nofollow]")
      - ::none:: [Diseño web seacomoseo.com](https://seacomoseo.com/)
  certificates:
  - img: /u/otros/iso-9001-14001.svg
    ratio: 4/1
  - img: /u/otros/a3e.png
    ratio: 6/1
    url: https://a3e.es/organization/7090/
  - img: /u/otros/cae.svg
    ratio: 3/1
    url: https://www.miteco.gob.es/es/energia/eficiencia/cae/agentes.html
